speeds <- read.csv("/tmp/output.csv")

plots <- list()
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = minutesDay, y = speed)) + geom_point() + facet_wrap(~schoolfr)
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = minutesDay, y = speed)) + geom_point() + facet_wrap(~holidaySizefr)
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = minutesDay, y = speed)) + geom_point() + facet_wrap(~weekday)
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = as.numeric(timestamp), y = speed)) + geom_point(aes(color=as.factor(month)))
# do.call(grid.arrange, c(plots, nrow=3))

plots <- list()
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = timestamp, y = speed)) + geom_point(shape = 1) 
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = minutesDay, y = speed)) + geom_point(shape = 1) 
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = minutesHour, y = speed)) + geom_point(shape = 1) 
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = weekday, y = speed)) + geom_boxplot()
# do.call(grid.arrange, c(plots, list(ncol = 2)))

plots <- list()
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = holidayfr, y = speed)) + geom_boxplot()
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = holidaych, y = speed)) + geom_boxplot()
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = schoolfr, y = speed)) + geom_boxplot()
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = schoolch, y = speed)) + geom_boxplot()
do.call(grid.arrange, c(plots, list(ncol = 2)))

plots <- list()
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = humidity, y = speed)) + geom_point(shape = 1) 
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = pressure, y = speed)) + geom_point(shape = 1) 
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = temperature, y = speed)) + geom_point(shape = 1) 
plots[[length(plots)+1]] <- ggplot(data = speeds, aes(x = weather, y = speed)) + geom_boxplot()
# do.call(grid.arrange, c(plots, list(ncol = 2)))
