BEGIN;
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170616222,'GRVI');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170619082,'MATG');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170619860,'CAND');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170623599,'PAAN');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170625235,'ADOU');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170627563,'BRET');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170629175,'AGLA');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170629760,'CLJO');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1163135167,'PREV');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170638463,'HAMA');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170639844,'CHTE');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170640218,'PBRU');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1186330722,'FEMA');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170645798,'AJUR');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1170647629,'COLX');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('L. INTERNATIONAL', 'O', 1171737396,'LYIN');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170616222,'GRVI');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170618616,'MATG');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170619731,'CAND');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170623599,'PAAN');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170625404,'ADOU');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170627846,'BRET');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170629236,'AGLA');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170629662,'CLJO');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1163135117,'PREV');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170638362,'HAMA');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170639773,'CHTE');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1114933442,'PBRU');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1114926724,'FEMA');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170645974,'AJUR');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1170647500,'COLX');
INSERT INTO app.tpgstop2 (destination, line, osmid, tpgcode) VALUES ('MEYRIN-GRAVIERE', 'O', 1171737396,'LYIN');
COMMIT;